In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df["Category"].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df["spam"] = df['Category'].apply(lambda x:1 if x == "spam" else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
df.shape

(5572, 3)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df['Message'],df['spam'],test_size=0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [ ]:
type(x_train)

pandas.core.series.Series

In [ ]:
x_train[:4]

1234                   Lol ok. I'll snatch her purse too.
3457                         Ok. I.ll do you right later.
3496    Wan2 win a Meet+Greet with Westlife 4 U or a m...
3108    Hi. Happy New Year. I dont mean to intrude but...
Name: Message, dtype: object

***Create bag of words representation using CountVectorizer***

In [ ]:
x_train.values

array(["Lol ok. I'll snatch her purse too.",
       'Ok. I.ll do you right later.',
       'Wan2 win a Meet+Greet with Westlife 4 U or a m8? They are currently on what tour? 1)Unbreakable, 2)Untamed, 3)Unkempt. Text 1,2 or 3 to 83049. Cost 50p +std text',
       ...,
       'Good afternoon, my love ! Any job prospects ? Are you missing me ? What do you do ? Are you being lazy and bleak, hmmm ? Or happy and filled with my love ?',
       'Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?',
       'Prof: you have passed in all the papers in this sem congrats . . . . Student: Enna kalaachutaarama..!! Prof:???? Gud mrng!'],
      dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
x_train_cv =v.fit_transform(x_train.values)
x_train_cv

<4457x7743 sparse matrix of type '<class 'numpy.int64'>'
	with 59393 stored elements in Compressed Sparse Row format>

In [ ]:
print(x_train_cv)

  (0, 4176)	1
  (0, 4912)	1
  (0, 4151)	1
  (0, 6268)	1
  (0, 3387)	1
  (0, 5504)	1
  (0, 6966)	1
  (1, 4912)	1
  (1, 4151)	1
  (1, 2354)	1
  (1, 7704)	1
  (1, 5776)	1
  (1, 4015)	1
  (2, 7373)	1
  (2, 7520)	1
  (2, 4421)	1
  (2, 3215)	1
  (2, 7547)	1
  (2, 7468)	1
  (2, 4968)	2
  (2, 4278)	1
  (2, 6834)	1
  (2, 1031)	1
  (2, 2108)	1
  (2, 4930)	1
  :	:
  (4455, 1573)	1
  (4455, 835)	1
  (4455, 1743)	1
  (4455, 3336)	1
  (4455, 2840)	1
  (4455, 6127)	1
  (4455, 5230)	1
  (4455, 4088)	1
  (4455, 552)	1
  (4456, 7704)	1
  (4456, 6848)	1
  (4456, 3622)	2
  (4456, 3333)	1
  (4456, 6812)	1
  (4456, 3239)	1
  (4456, 893)	1
  (4456, 4609)	1
  (4456, 1955)	1
  (4456, 5094)	1
  (4456, 6530)	1
  (4456, 5437)	2
  (4456, 5068)	1
  (4456, 6000)	1
  (4456, 2583)	1
  (4456, 3872)	1


In [ ]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
x_train_cv.shape

(4457, 7743)

In [ ]:
v.get_feature_names_out()[1771]

'chik'

In [ ]:
len(v.vocabulary_)

7743

In [ ]:
x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.where(x_train_np[0] != 0)

(array([3387, 4151, 4176, 4912, 5504, 6268, 6966]),)

In [ ]:
x_train[:4]

1234                   Lol ok. I'll snatch her purse too.
3457                         Ok. I.ll do you right later.
3496    Wan2 win a Meet+Greet with Westlife 4 U or a m...
3108    Hi. Happy New Year. I dont mean to intrude but...
Name: Message, dtype: object

In [ ]:
# x_train[:4][4740]

In [ ]:
x_train_np[0][3171]

0

***Train the naive bayes model***

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [ ]:
x_test_cv = v.transform(x_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       957
           1       0.99      0.90      0.94       158

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



*some other*

In [ ]:

emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [ ]:
email_count = v.transform(emails)
model.predict(email_count)

array([0, 1])

***Train the model using sklearn pipeline and reduce number of lines of code***

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ("vectorizer",CountVectorizer()),
    ("NB",MultinomialNB())
])

In [ ]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('NB', MultinomialNB())])

In [ ]:
y_pred = clf.predict(x_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       957
           1       0.99      0.90      0.94       158

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



***Exercise***

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!unzip "/content/drive/MyDrive/nlp files/imdb-dataset-of-50k-movie-reviews.zip"

Archive:  /content/drive/MyDrive/nlp files/imdb-dataset-of-50k-movie-reviews.zip
replace IMDB Dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: no


In [ ]:
df = pd.read_csv("/content/IMDB Dataset.csv")
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df["num_sen"] = df["sentiment"].apply(lambda x:1 if x == "positive" else 0)
df.head()

review sentiment  num_sen
0  One of the other reviewers has mentioned that ...  positive        1
1  A wonderful little production. <br /><br />The...  positive        1
2  I thought this was a wonderful way to spend ti...  positive        1
3  Basically there's a family where a little boy ...  negative        0
4  Petter Mattei's "Love in the Time of Money" is...  positive        1

In [ ]:
df['num_sen'].value_counts()

num_sen
1    25000
0    25000
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df['review'],df['num_sen'],test_size=0.2)

***For RandomForestClassification***

In [ ]:
from sklearn.ensemble import RandomForestClassifier # Make sure this is in the same cell
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer

model = Pipeline([
    ("vecctorizer",CountVectorizer()),
    ("rf",RandomForestClassifier()) # You need to call the constructor here
])

In [ ]:
model.fit(x_train,y_train)

Pipeline(steps=[('vecctorizer', CountVectorizer()),
                ('rf', RandomForestClassifier())])

In [ ]:
y_pred = model.predict(x_test)

# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.84      0.84      5001
           1       0.84      0.85      0.85      4999

    accuracy                           0.84     10000
   macro avg       0.85      0.85      0.84     10000
weighted avg       0.85      0.84      0.84     10000



***For KNN Algoritm***

In [ ]:
from sklearn.neighbors import KNeighborsClassifier  # Make sure this is in the same cell
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer

model_knn = Pipeline([
    ("vecctorizer",CountVectorizer()),
    ("rf",KNeighborsClassifier(n_neighbors=5, metric='euclidean', p=2 )) # You need to call the constructor here
])

In [ ]:
model_knn.fit(x_train,y_train)

Pipeline(steps=[('vecctorizer', CountVectorizer()),
                ('rf', KNeighborsClassifier(metric='euclidean'))])

In [ ]:
y_pred = model_knn.predict(x_test)

# classification report
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.64      0.57      0.60      5001
           1       0.61      0.68      0.65      4999

    accuracy                           0.63     10000
   macro avg       0.63      0.63      0.63     10000
weighted avg       0.63      0.63      0.63     10000



***For Multinomial Naive Bayes***

In [ ]:
from sklearn.naive_bayes import MultinomialNB # Make sure this is in the same cell
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer

model_mnb = Pipeline([
    ("vecctorizer",CountVectorizer()),
    ("rf",MultinomialNB()) # You need to call the constructor here
])

In [ ]:
model_mnb.fit(x_train,y_train)


Pipeline(steps=[('vecctorizer', CountVectorizer()), ('rf', MultinomialNB())])

In [ ]:
y_pred = model_mnb.predict(x_test)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.83      0.87      0.85      5001
           1       0.86      0.82      0.84      4999

    accuracy                           0.84     10000
   macro avg       0.85      0.84      0.84     10000
weighted avg       0.85      0.84      0.84     10000

